// AUTO-GENERATED BY build-kb.ts - DO NOT EDIT
export const KNOWLEDGE = {
  "regions": {
    "KA_DHARWAD": {
      "id": "KA_DHARWAD",
      "name_en": "Dharwad",
      "name_kn": "ಧಾರವಾಡ",
      "parent": "KA",
      "agro_climatic_zone": "northern_transition",
      "weather_stations": [
        "dharwad",
        "hubballi",
        "navalgund"
      ],
      "centroid": {
        "lat": 15.46,
        "lon": 75.01
      },
      "soils_present": [
        "black_cotton",
        "red_loam"
      ],
      "dominant_soil": null,
      "sources": [
        "UAS Dharwad POP 2022",
        "IMD normals 1991-2020"
      ],
      "normal_annual_rainfall_mm": 780,
      "sowing_window": {
        "kharif": [
          "W23",
          "W28"
        ],
        "rabi": [
          "W38",
          "W42"
        ]
      },
      "pest_pressure": {
        "fall_armyworm": "endemic"
      },
      "taluks": [
        "Dharwad",
        "Hubballi",
        "Kalghatgi",
        "Kundgol",
        "Navalgund",
        "Annigeri",
        "Alnavar"
      ]
    }
  },
  "params": {
    "crop_maize": {
      "name": "Maize Crop Parameters",
      "values": [
        {
          "when": {},
          "value": {
            "tbase": 10,
            "tcap": 30,
            "kc_ini": 0.3,
            "kc_mid": 1.2,
            "kc_end": 0.35,
            "mad_p": 0.55,
            "root_depth": 1.2
          }
        }
      ]
    },
    "crop_maize_constants": {
      "name": "crop_maize_constants",
      "unit": "dimensionless",
      "source": {
        "doc": "FAO-56 Crop Evapotranspiration",
        "page": 1,
        "year": 1998
      },
      "agronomist_review": "pending",
      "values": [
        {
          "when": {},
          "value": {
            "Tbase": 10,
            "Tmax_cap": 30,
            "heat_stress_threshold_c": 35,
            "MAD": 0.55,
            "Kc": {
              "VE": 0.3,
              "V4": 0.4,
              "V8": 0.7,
              "VT": 1.2,
              "R1": 1.2,
              "R3": 1,
              "R6": 0.6
            },
            "GDD": {
              "VE": 60,
              "V4": 300,
              "V8": 550,
              "VT": 900,
              "R1": 1000,
              "R3": 1250,
              "R6": 1500
            },
            "root_zone_depth_m": {
              "VE": 0.3,
              "VT": 1
            }
          }
        }
      ]
    },
    "faw_etl": {
      "name": "faw_economic_threshold",
      "unit": "percent_plants_damaged",
      "source": {
        "doc": "ICAR-IIMR FAW Advisory",
        "page": 7,
        "year": 2023
      },
      "agronomist_review": "pending",
      "values": [
        {
          "when": {
            "pest_pressure": "endemic"
          },
          "value": 10
        },
        {
          "when": {},
          "value": 20,
          "confidence": "MEDIUM"
        }
      ]
    },
    "irrigation_rain_threshold": {
      "name": "irrigation_rain_threshold",
      "unit": "mm",
      "source": {
        "doc": "FAO-56 Crop Evapotranspiration",
        "page": 1,
        "year": 1998
      },
      "agronomist_review": "pending",
      "values": [
        {
          "when": {},
          "value": 20
        }
      ]
    },
    "n_schedule": {
      "name": "nitrogen_top_dressing",
      "unit": "kg_urea_per_acre",
      "source": {
        "doc": "UAS Dharwad Package of Practices",
        "page": 112,
        "year": 2022
      },
      "agronomist_review": "Approved by Dharwad KVK",
      "unknown_key_policy": {
        "strategy": "conservative_low",
        "ask_if_spread_exceeds": 0.2
      },
      "values": [
        {
          "when": {
            "stage": "V4",
            "agro_climatic_zone": "northern_transition"
          },
          "value": 25
        },
        {
          "when": {
            "stage": "V6",
            "agro_climatic_zone": "northern_transition"
          },
          "value": 25
        },
        {
          "when": {
            "stage": "V4"
          },
          "value": 20
        },
        {
          "when": {
            "stage": "V6"
          },
          "value": 20
        },
        {
          "when": {
            "stage": "VT"
          },
          "value": 10
        },
        {
          "when": {
            "stage": "R1"
          },
          "value": 10
        },
        {
          "when": {},
          "value": 0
        }
      ]
    },
    "pesticide_doses": {
      "name": "pesticide_recommended_agent",
      "unit": "chemical_and_dose",
      "source": {
        "doc": "ICAR-IIMR FAW Advisory",
        "page": 8,
        "year": 2023
      },
      "agronomist_review": "pending",
      "values": [
        {
          "when": {
            "pest_name": "faw",
            "pest_pressure": "endemic"
          },
          "value": "Emamectin benzoate 5% SG (0.4 g/litre)"
        },
        {
          "when": {
            "pest_name": "faw"
          },
          "value": "Chlorantraniliprole 18.5 SC (0.4 ml/litre)"
        },
        {
          "when": {},
          "value": "standard pesticide"
        }
      ]
    }
  },
  "rulepacks": {
    "faw_risk_v1": {
      "rule": "faw_risk_v1",
      "intent": "pest_advice",
      "priority": 90,
      "when": {
        "stage": [
          "VE",
          "V4",
          "V8"
        ],
        "and_any": [
          "dry_spell_days >= 5",
          "tmax_7d_mean between [25, 32]"
        ],
        "modifiers": [
          {
            "rh_morning_7d_mean > 70": "+1 risk level"
          }
        ]
      },
      "action_by_risk": {
        "moderate": "scout 10 plants x 5 spots; count whorl damage %; install 5 pheromone traps/acre",
        "high": "as above + act if whorl damage exceeds ETL"
      },
      "etl": {
        "early_whorl_V3_V6": "5% damaged plants",
        "late_whorl_V7_V8": "10-20% damaged plants"
      },
      "control": "knowledge_card://faw_ipm_v1",
      "confidence": "rule_based",
      "sources": [
        "ICAR-IIMR FAW advisory",
        "UAS-Dharwad POP"
      ],
      "agronomist_review": "approved"
    },
    "fertilizer_n": {
      "name": "Fertilizer Rules",
      "rules": [
        {
          "id": "FERT_N_TOP_DRESSING_V4",
          "intent": "fertilizer_dose",
          "type": "stage_fertilizer",
          "stage": [
            "vegetative"
          ],
          "action": {
            "advise": "APPLY_FERTILIZER",
            "ruleId": "FERT_N_TOP_DRESSING_V4",
            "reason": "First nitrogen top-dressing is recommended at the vegetative stage (30-40 days). Apply PLACEHOLDER_UREA_DOSE kg/ha Urea.",
            "source": "PLACEHOLDER_UAS"
          }
        },
        {
          "id": "FERT_N_LATE",
          "intent": "fertilizer_dose",
          "type": "fallback",
          "action": {
            "advise": "WAIT",
            "ruleId": "FERT_N_LATE",
            "reason": "Nitrogen top-dressing is not recommended at this stage.",
            "source": "PLACEHOLDER_UAS"
          }
        }
      ]
    },
    "irrigation": {
      "name": "Irrigation Rules",
      "rules": [
        {
          "id": "IRR_R1_FORECAST_RAIN",
          "intent": "irrigation_advice",
          "type": "forecast",
          "threshold": 15,
          "action": {
            "advise": "WAIT",
            "ruleId": "IRR_R1_FORECAST_RAIN",
            "reason": "Significant rainfall (>15mm) expected in the next 72 hours.",
            "source": "PLACEHOLDER_RULES"
          }
        },
        {
          "id": "IRR_R2_CRITICAL_STAGE",
          "intent": "irrigation_advice",
          "type": "critical_stage_depletion",
          "stage": [
            "flowering",
            "yield_formation"
          ],
          "threshold": 0.4,
          "action": {
            "advise": "IRRIGATE",
            "ruleId": "IRR_R2_CRITICAL_STAGE",
            "reason": "Crop is in a critical stage (flowering/yield formation) and soil moisture depletion exceeds critical threshold (40% TAW).",
            "source": "PLACEHOLDER_RULES"
          }
        },
        {
          "id": "IRR_R3_STANDARD_DEPLETION",
          "intent": "irrigation_advice",
          "type": "standard_depletion",
          "action": {
            "advise": "IRRIGATE",
            "ruleId": "IRR_R3_STANDARD_DEPLETION",
            "reason": "Soil moisture depletion exceeds standard Management Allowed Depletion (MAD).",
            "source": "PLACEHOLDER_RULES"
          }
        },
        {
          "id": "IRR_R4_NO_STRESS",
          "intent": "irrigation_advice",
          "type": "fallback",
          "action": {
            "advise": "WAIT",
            "ruleId": "IRR_R4_NO_STRESS",
            "reason": "Soil moisture is adequate and crop is not under stress. No irrigation needed.",
            "source": "PLACEHOLDER_RULES"
          }
        }
      ]
    },
    "pest_faw": {
      "name": "Fall Armyworm Rules",
      "rules": [
        {
          "id": "FAW_R1_ETL",
          "intent": "pest_management",
          "type": "etl_threshold",
          "threshold": 10,
          "action": {
            "advise": "SCOUT",
            "ruleId": "FAW_R1_ETL",
            "reason": "Infestation is at or above the Economic Threshold Level (10%). Please scout and consult your local RSK. No chemical dose is provided here.",
            "source": "PLACEHOLDER_ICAR"
          }
        },
        {
          "id": "FAW_R2_MONITOR",
          "intent": "pest_management",
          "type": "fallback",
          "action": {
            "advise": "WAIT",
            "ruleId": "FAW_R2_MONITOR",
            "reason": "Infestation is below ETL. Continue monitoring the crop.",
            "source": "PLACEHOLDER_ICAR"
          }
        }
      ]
    },
    "sowing": {
      "name": "Sowing Rules",
      "rules": [
        {
          "id": "SOW_R1_RAIN",
          "intent": "sowing_window",
          "type": "rainfall_onset",
          "threshold": 25,
          "action": {
            "advise": "SOW",
            "ruleId": "SOW_R1_RAIN",
            "reason": "Rainfall has exceeded 25mm in the past/next 72 hours. Soil moisture is adequate for sowing.",
            "source": "PLACEHOLDER_UAS"
          }
        },
        {
          "id": "SOW_R2_DRY",
          "intent": "sowing_window",
          "type": "fallback",
          "action": {
            "advise": "WAIT",
            "ruleId": "SOW_R2_DRY",
            "reason": "Insufficient rainfall. Wait for a good soaking rain (>25mm) before sowing.",
            "source": "PLACEHOLDER_UAS"
          }
        }
      ]
    }
  }
};
