import fs from 'fs';
import path from 'path';
import yaml from 'yaml';
import { z } from 'zod';
import { zodToJsonSchema } from 'zod-to-json-schema';

const KNOWLEDGE_DIR = path.join(__dirname, '../knowledge');
const REGIONS_DIR = path.join(KNOWLEDGE_DIR, 'regions');
const PARAMS_DIR = path.join(KNOWLEDGE_DIR, 'params');
const RULEPACKS_DIR = path.join(KNOWLEDGE_DIR, 'rulepacks');
const OUT_FILE = path.join(__dirname, '../packages/core/src/knowledge_compiled.ts');
const SCHEMAS_DIR = path.join(__dirname, '../schemas');

// --- ZOD SCHEMAS ---

const RegionSchema = z.object({
    id: z.string(),
    name_en: z.string(),
    name_kn: z.string(),
    parent: z.string().optional(),
    agro_climatic_zone: z.string(),
    weather_stations: z.array(z.string()).optional(),
    centroid: z.object({ lat: z.number(), lon: z.number() }).optional(),
    soils_present: z.array(z.string()),
    dominant_soil: z.string().nullable().optional(),
    sources: z.array(z.string()).optional(),
}).catchall(z.any());

const ParamValueSchema = z.object({
    when: z.record(z.string(), z.any()),
    value: z.union([z.number(), z.string(), z.record(z.string(), z.any())]),
    confidence: z.string().optional(),
});

const ParamSchema = z.object({
    name: z.string().optional(),
    unit: z.string().optional(),
    source: z.any().optional(),
    agronomist_review: z.string().optional(),
    unknown_key_policy: z.object({
        strategy: z.enum(['conservative_low', 'conservative_high']),
        ask_if_spread_exceeds: z.number()
    }).optional(),
    values: z.array(ParamValueSchema)
});

function readYamlDir(dir: string) {
    if (!fs.existsSync(dir)) return {};
    const files = fs.readdirSync(dir).filter(f => f.endsWith('.yaml'));
    const result: any = {};
    for (const file of files) {
        const content = fs.readFileSync(path.join(dir, file), 'utf8');
        const parsed = yaml.parse(content);
        const name = file.replace('.yaml', '');
        result[name] = parsed;
    }
    return result;
}

function deepEqual(a: any, b: any) {
    return JSON.stringify(a) === JSON.stringify(b);
}

function checkParams(params: any) {
    for (const [paramId, paramDef] of Object.entries(params)) {
        const p = paramDef as z.infer<typeof ParamSchema>;
        
        // 1. Overlap Detection: No two 'when' blocks should be identical unless priority is defined
        // (For simplicity here, we just check strict equality of the 'when' object)
        const whenHashes = p.values.map(v => JSON.stringify(v.when, Object.keys(v.when).sort()));
        const uniqueHashes = new Set(whenHashes);
        if (uniqueHashes.size !== whenHashes.length) {
            throw new Error(`Overlap detected in parameter '${paramId}': Duplicate 'when' conditions found.`);
        }

        // 2. Coverage: Ensure there's a fallback (empty 'when' block)
        const hasFallback = p.values.some(v => Object.keys(v.when).length === 0);
        if (!hasFallback) {
            throw new Error(`Coverage hole detected in parameter '${paramId}': No fallback '{}' condition provided.`);
        }
    }
}

function build() {
    console.log('Compiling Knowledge Base...');
    
    // Read and Validate
    const rawRegions = readYamlDir(REGIONS_DIR);
    const rawParams = readYamlDir(PARAMS_DIR);
    const rawRulepacks = readYamlDir(RULEPACKS_DIR);

    const regions: Record<string, any> = {};
    const params: Record<string, any> = {};
    const rulepacks: Record<string, any> = {};

    for (const [id, data] of Object.entries(rawRegions)) {
        regions[id] = RegionSchema.parse(data);
    }
    for (const [id, data] of Object.entries(rawParams)) {
        params[id] = ParamSchema.parse(data);
    }
    for (const [id, data] of Object.entries(rawRulepacks)) {
        rulepacks[id] = data; // skip deep validation for now
    }

    // Advanced Checks
    checkParams(params);
    // Referential integrity check (e.g. soil types or agro zones) can be added here
    
    const compiled = { regions, params, rulepacks };
    const outContent = `// AUTO-GENERATED BY build-kb.ts - DO NOT EDIT\nexport const KNOWLEDGE = ${JSON.stringify(compiled, null, 2)};\n`;
    
    fs.writeFileSync(OUT_FILE, outContent, 'utf8');
    console.log(`Knowledge Base compiled to ${OUT_FILE}`);

    // Output JSON Schemas
    if (!fs.existsSync(SCHEMAS_DIR)) fs.mkdirSync(SCHEMAS_DIR, { recursive: true });
    fs.writeFileSync(
        path.join(SCHEMAS_DIR, 'param.schema.json'), 
        JSON.stringify(zodToJsonSchema(ParamSchema as any, 'ParamSchema'), null, 2), 
        'utf8'
    );
    console.log('JSON Schemas generated.');
}

build();
